##### anchor area START #####
x-misc:
  regex-include-info-node: &x-regex-include-info-node '(?i)^ℹ️ .+: \d.+ (KB|MB|GB|TB) \/ \d.+ (KB|MB|GB|TB).*$'
  regex-exclude-info-node: &x-regex-exclude-info-node '(?i)^(?!ℹ️ .+: \d.+ (KB|MB|GB|TB) \/ \d.+ (KB|MB|GB|TB)).*$'

x-dns:
  system: &x-dns-system
    - system
  china: &x-dns-china
    - 119.29.29.29
    - 223.5.5.5
  overseas: &x-dns-overseas
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query

x-proxy-providers: &x-proxy-providers
  type: http
  interval: 3600
  health-check:
    enable: true
    url: https://cp.cloudflare.com
    interval: 300

x-proxy-groups:
  control-select-proxy: &x-pg-control-select-proxy
    type: select
    proxies:
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择
      - 🎩 私有节点
      - 🏠 家宽节点
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选
      # - 🇮🇳 印度优选
      # - 🇬🇧 英国优选
      # - 🇫🇷 法国优选
      # - 🇨🇦 加拿大优选
      # - 🇦🇺 澳大利亚优选
      # - 🇷🇺 俄罗斯优选
      # - 🇹🇷 土耳其优选
      # - 🇦🇷 阿根廷优选
      # - 🇧🇷 巴西优选
      # - 🇨🇳 回国选择
  control-select-direct: &x-pg-control-select-direct
    type: select
    proxies:
      - 🎯 全部直连
      - 🔰 节点选择
      - ✈️ 手动选择
      - 🎩 私有节点
      - 🏠 家宽节点
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选
      # - 🇮🇳 印度优选
      # - 🇬🇧 英国优选
      # - 🇫🇷 法国优选
      # - 🇨🇦 加拿大优选
      # - 🇦🇺 澳大利亚优选
      # - 🇷🇺 俄罗斯优选
      # - 🇹🇷 土耳其优选
      # - 🇦🇷 阿根廷优选
      # - 🇧🇷 巴西优选
      # - 🇨🇳 回国选择
  control-select-private: &x-pg-control-select-private
    type: select
    proxies:
      - 🎩 私有节点
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择
      - 🏠 家宽节点
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选
      # - 🇮🇳 印度优选
      # - 🇬🇧 英国优选
      # - 🇫🇷 法国优选
      # - 🇨🇦 加拿大优选
      # - 🇦🇺 澳大利亚优选
      # - 🇷🇺 俄罗斯优选
      # - 🇹🇷 土耳其优选
      # - 🇦🇷 阿根廷优选
      # - 🇧🇷 巴西优选
      # - 🇨🇳 回国选择
  control-select-clean: &x-pg-control-select-clean
    type: select
    proxies:
      - 🏠 家宽节点
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择
      - 🎩 私有节点
      - 📥 高耗流量
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选
      # - 🇮🇳 印度优选
      # - 🇬🇧 英国优选
      # - 🇫🇷 法国优选
      # - 🇨🇦 加拿大优选
      # - 🇦🇺 澳大利亚优选
      # - 🇷🇺 俄罗斯优选
      # - 🇹🇷 土耳其优选
      # - 🇦🇷 阿根廷优选
      # - 🇧🇷 巴西优选
      # - 🇨🇳 回国选择
  control-select-all: &x-pg-control-select-all
    type: select
    include-all: true
    filter: *x-regex-exclude-info-node
  region-urltest: &x-pg-region-urltest
    type: url-test
    url: "https://www.gstatic.com/generate_204"
    interval: 300
    lazy: true
    include-all: true
    # hidden: true
  region-select: &x-pg-region-select
    type: select
    include-all: true
    # hidden: true

x-rule-providers:
  yaml: &x-rp-yaml
    type: http
    format: yaml
    interval: 86400
  text: &x-rp-text
    type: http
    format: text
    interval: 86400
  mrs: &x-rp-mrs
    type: http
    format: mrs
    interval: 86400
##### anchor area END #####

##### config area START #####
# general
mode: rule
ipv6: false
mixed-port: 7890
allow-lan: true
lan-allowed-ips:
  - 127.0.0.1/32
  - 192.168.0.0/16
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 100.64.0.0/10
tun:
  enable: true
  mtu: 1500
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
# meta general
external-controller: 127.0.0.1:9090
unified-delay: true
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"

## meta sniffer (for redir-host)
# sniffer:
#   enable: true
#   sniff:
#     HTTP:
#       ports: [80, 8080-8880]
#       override-destination: true
#     TLS:
#       ports: [443, 8443]
#     QUIC:
#       ports: [443, 8443]
#   force-domain:
#     - "+.netflix.com"
#     - "+.nflxvideo.net"
#     - "+.amazonaws.com"
#     - "+.media.dssott.com"
#   skip-domain:
#     - '+.apple.com'
#     - Mijia Cloud
#     - dlg.io.mi.com
#     - +.oray.com
#     - +.sunlogin.net
#     - +.push.apple.com

# network stack
dns: &base-dns
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - "myip.opendns.com"
    - "resolver1.opendns.com"
    - "geosite:connectivity-check"
    - "geosite:private"
    - "rule-set:MyDirect"
    - "rule-set:MyDirect02"
    - "geosite:tailscale"
    - "geosite:tracker"
    - "geosite:category-pt"
    - "geosite:category-games"
    - "rule-set:GoogleVoice"
    - "geosite:category-speedtest"
    - "geosite:category-finance"
    - "rule-set:FinanceExtra"
    - "geosite:cn"
  respect-rules: true
  nameserver: *x-dns-overseas
  proxy-server-nameserver: *x-dns-china
  proxy-server-nameserver-policy:
    "+.cloud-nodes.com": ["140.205.1.13", "124.221.68.73:1053"]
  nameserver-policy:
    "geosite:private": *x-dns-china
    "rule-set:MyDirect": *x-dns-china
    "rule-set:MyDirect02": *x-dns-china
    "geosite:tailscale": *x-dns-china
    "geosite:tracker": *x-dns-china
    "geosite:category-pt": *x-dns-china
    "geosite:category-game-platforms-download": *x-dns-china
    "geosite:category-games@cn": *x-dns-china
    "geosite:category-dev@cn": *x-dns-china
    "geosite:category-finance@cn": *x-dns-china
    "geosite:microsoft@cn": *x-dns-china
    "rule-set:AppleCDN": *x-dns-china
    "geosite:cn": *x-dns-china

# proxies
proxy-groups: &base-proxy-groups ## control groups
  - name: ℹ️ 订阅信息
    <<: *x-pg-control-select-all
    filter: *x-regex-include-info-node
  - name: 🔰 节点选择
    type: select
    proxies:
      - ✈️ 手动选择
      - 🎯 全部直连
      - 🎩 私有节点
      - 🏠 家宽节点
      - 🇭🇰 香港优选
      - 🇺🇸 美国优选
      - 🇯🇵 日本优选
      - 🇹🇼 台湾优选
      - 🇸🇬 新加坡优选
      - 🇰🇷 韩国优选
      # - 🇮🇳 印度优选
      # - 🇬🇧 英国优选
      # - 🇫🇷 法国优选
      # - 🇨🇦 加拿大优选
      # - 🇦🇺 澳大利亚优选
      # - 🇷🇺 俄罗斯优选
      # - 🇹🇷 土耳其优选
      # - 🇦🇷 阿根廷优选
      # - 🇧🇷 巴西优选
      # - 🇨🇳 回国选择

  - name: ✈️ 手动选择
    <<: *x-pg-control-select-all

  - name: 🎩 私有节点
    <<: *x-pg-control-select-all
    filter: "(?i:Private|PRIV)"

  - name: 🏠 家宽节点
    <<: *x-pg-control-select-all
    filter: "(?i:家宽|Clean)"

  - name: 📥 高耗流量
    <<: *x-pg-control-select-all
    proxies:
      - 🔰 节点选择
      - 🎯 全部直连
      - ✈️ 手动选择
      - 🎩 私有节点
      - 🏠 家宽节点

  - name: 📶 Speedtest
    <<: *x-pg-control-select-all
    proxies:
      - 🎯 全部直连
      - 🔰 节点选择
      - ✈️ 手动选择
      - 🎩 私有节点
      - 🏠 家宽节点
      - 📥 高耗流量

  - name: 🐟 漏网之鱼
    <<: *x-pg-control-select-proxy

  - name: 🎯 全部直连
    type: select
    hidden: true
    proxies:
      - DIRECT

  ## services groups
  - name: 🍎 Apple
    <<: *x-pg-control-select-direct

  - name: 🍭 Google
    <<: *x-pg-control-select-proxy

  - name: Ⓜ️ Microsoft
    <<: *x-pg-control-select-proxy

  - name: ☁️ Onedrive
    <<: *x-pg-control-select-direct

  - name: 💻 Developer
    <<: *x-pg-control-select-proxy

  - name: ✨ GenAI
    <<: *x-pg-control-select-proxy

  - name: 🎮 Games
    <<: *x-pg-control-select-direct

  - name: 🎮 Nintendo
    <<: *x-pg-control-select-direct

  - name: 🎮 PlayStation
    <<: *x-pg-control-select-direct

  - name: 🎮 Steam
    <<: *x-pg-control-select-proxy

  - name: 🎵 Spotify
    <<: *x-pg-control-select-proxy

  - name: 🎵 Qobuz
    <<: *x-pg-control-select-proxy

  - name: 🎥 Emby Providers
    <<: *x-pg-control-select-all
    filter: "(?i:Emby)"

  - name: 🎥 Youtube
    <<: *x-pg-control-select-proxy

  - name: 🎥 Netflix
    <<: *x-pg-control-select-proxy

  - name: 🎥 Apple TV
    <<: *x-pg-control-select-proxy

  - name: 🎥 TikTok
    <<: *x-pg-control-select-proxy

  - name: 💰 Finance
    <<: *x-pg-control-select-proxy

  - name: 💰 Crypto
    <<: *x-pg-control-select-proxy

  - name: 💬 Telegram
    <<: *x-pg-control-select-proxy

  - name: 𝕏 Twitter
    <<: *x-pg-control-select-proxy

  - name: 🈲 Restricted
    <<: *x-pg-control-select-private

  ## region groups
  - name: 🇭🇰 香港优选
    <<: *x-pg-region-urltest
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇭🇰|\bHK[G]?\b|Hong.*?Kong|\bHKT\b|\bHKBN\b|\bHGC\b|\bWTT\b|\bCMI\b|[^-]港)).*$'

  - name: 🇺🇸 美国优选
    <<: *x-pg-region-urltest
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇺🇸|\bUS[A]?\b|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)).*$'

  - name: 🇯🇵 日本优选
    <<: *x-pg-region-urltest
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇯🇵|\bJP[N]?\b|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-尼]日)).*$'

  - name: 🇹🇼 台湾优选
    <<: *x-pg-region-urltest
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇹🇼|\bTW[N]?\b|Taiwan|新北|彰化|\bCHT\b|台湾|[^-]台|\bHINET\b)).*$'

  - name: 🇸🇬 新加坡优选
    <<: *x-pg-region-urltest
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇸🇬|\bSG[P]?\b|Singapore|新加坡|狮城)).*$'

  - name: 🇰🇷 韩国优选
    <<: *x-pg-region-urltest
    filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇰🇷|\bK[O]?R\b|Korea|首尔|韩|韓)).*$'

  # - name: 🇮🇳 印度优选
  #   <<: *x-pg-region-urltest
  #   filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇮🇳|\bIN[D]?\b|India|Mumbai|印度|孟买|加尔各答|贾坎德|泰米尔纳德)).*$'

  # - name: 🇬🇧 英国优选
  #   <<: *x-pg-region-urltest
  #   filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇬🇧|\bUK\b|England|United.*?Kingdom|London|英国|[^-]英|伦敦)).*$'

  # - name: 🇫🇷 法国优选
  #   <<: *x-pg-region-urltest
  #   filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇫🇷|\bFR[A]?\b|France|Paris|法国|巴黎)).*$'

  # - name: 🇨🇦 加拿大优选
  #   <<: *x-pg-region-urltest
  #   filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇨🇦|\bCA[N]?\b|Canada|Toronto|Montreal|Vancouver|加拿大|蒙特利尔|温哥华|楓葉|枫叶)).*$'

  # - name: 🇦🇺 澳大利亚优选
  #   <<: *x-pg-region-urltest
  #   filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇦🇺|\bAU[S]?\b|Australia|Sydney|澳大利亚|澳洲|悉尼)).*$'

  # - name: 🇷🇺 俄罗斯优选
  #   <<: *x-pg-region-urltest
  #   filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇷🇺|\bRU[S]?\b|Russia|Moscow|Petersburg|Siberia|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|哈巴罗夫斯克|俄罗斯|[^-]俄)).*$'

  # - name: 🇹🇷 土耳其优选
  #   <<: *x-pg-region-urltest
  #   filter: "(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇹🇷|Turkey|土耳其|伊斯坦布尔)).*$"

  # - name: 🇦🇷 阿根廷优选
  #   <<: *x-pg-region-urltest
  #   filter: "(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇦🇷|Argentina|阿根廷)).*$"

  # - name: 🇧🇷 巴西优选
  #   <<: *x-pg-region-urltest
  #   filter: "(?i)^(?!.*(?:专用|noauto))(?=.*(?:🇧🇷|Brazil|巴西|Paulo|圣保罗|里约热内卢)).*$"

  # - name: 🇨🇳 回国选择
  #   <<: *x-pg-control-select-all
  #   filter: '(?i)^(?!.*(?:专用|noauto))(?=.*(?:\bC[H]?N\b|China|回国|中国[^-]|江苏[^-]|北京[^-]|上海[^-]|广州[^-]|深圳[^-]|杭州[^-]|常州[^-]|徐州[^-]|青岛[^-]|宁波[^-]|镇江[^-]|成都[^-]|back)).*$'

rule-providers: &base-rule-providers
  AdobeTelemetry:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/ignaciocastro/a-dove-is-dumb@main/pihole.txt
  MyDirect:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/MyDirect.list
  MyDirect02:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/list/myCN.list
  MyProxy:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/MyProxy.list
  MyProxy02:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/list/foreign.list
  ProxyHighBandwidth:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/ProxyHighBandwidth.list
  GoogleVoice:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/GoogleVoice.list
  Qobuz:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/Qobuz.list
  RestrictedZones:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/gz4zzxc/rule@main/Clash/list/fallback.list
  GenAIExtra:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/GenAIExtra.list
  CryptoExtra:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/CryptoExtra.list
  FinanceExtra:
    <<: *x-rp-text
    behavior: domain
    url: https://testingcf.jsdelivr.net/gh/jimlee2048/atc-config@main/clash/rules/FinanceExtra.list
  AppleCDN:
    <<: *x-rp-text
    behavior: domain
    url: https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt

rules: &base-rules
  # domain > classical > ipcidr
  # 1. local
  - GEOSITE,private,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  # 2. block
  - RULE-SET,AdobeTelemetry,REJECT
  # 3. custom override
  - RULE-SET,MyDirect,DIRECT
  - RULE-SET,MyDirect02,DIRECT
  - RULE-SET,MyProxy,🔰 节点选择
  - RULE-SET,MyProxy02,🔰 节点选择
  # 4. main: p1
  - GEOSITE,tailscale,DIRECT
  - GEOSITE,tracker,DIRECT
  - GEOSITE,category-pt,DIRECT
  - GEOSITE,category-speedtest,📶 Speedtest
  - RULE-SET,ProxyHighBandwidth,📥 高耗流量
  - GEOSITE,category-game-platforms-download,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,category-dev@cn,DIRECT
  - GEOSITE,category-finance@cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - RULE-SET,AppleCDN,DIRECT
  # 5. main: p2
  - GEOSITE,bing,🇺🇸 美国优选
  - GEOSITE,onedrive,☁️ Onedrive
  - RULE-SET,GoogleVoice,🇺🇸 美国优选
  - GEOSITE,telegram,💬 Telegram
  - GEOIP,telegram,💬 Telegram,no-resolve
  - GEOSITE,twitter,𝕏 Twitter
  - GEOIP,twitter,𝕏 Twitter,no-resolve
  - GEOSITE,nintendo,🎮 Nintendo
  - GEOSITE,playstation,🎮 PlayStation
  - GEOSITE,steam,🎮 Steam
  - GEOSITE,youtube,🎥 Youtube
  - GEOSITE,netflix,🎥 Netflix
  - GEOIP,netflix,🎥 Netflix,no-resolve
  - GEOSITE,apple-tvplus,🎥 Apple TV
  - GEOSITE,bahamut,🇹🇼 台湾优选
  - GEOSITE,tiktok,🎥 TikTok
  - GEOSITE,category-emby,🎥 Emby Providers
  - GEOSITE,spotify,🎵 Spotify
  - RULE-SET,Qobuz,🎵 Qobuz
  # 6. main: p3
  - RULE-SET,RestrictedZones,🈲 Restricted
  - GEOSITE,category-games-!cn,🎮 Games
  - GEOSITE,category-dev,💻 Developer
  - GEOSITE,category-ai-!cn,✨ GenAI
  - RULE-SET,GenAIExtra,✨ GenAI
  - GEOSITE,category-cryptocurrency,💰 Crypto
  - RULE-SET,CryptoExtra,💰 Crypto
  - GEOSITE,category-finance,💰 Finance
  - RULE-SET,FinanceExtra,💰 Finance
  # 7. main: p4
  - GEOSITE,microsoft,Ⓜ️ Microsoft
  - GEOSITE,google,🍭 Google
  - GEOIP,google,🍭 Google,no-resolve
  - GEOSITE,apple,🍎 Apple
  # 8. final
  - GEOSITE,cn,DIRECT
  - GEOSITE,geolocation-!cn,🔰 节点选择
  - GEOIP,cn,DIRECT,no-resolve
  - DST-PORT,80,🐟 漏网之鱼
  - DST-PORT,443,🐟 漏网之鱼
  - DST-PORT,853,🐟 漏网之鱼
  - MATCH,DIRECT

###### config area END #####
