# dns
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  # enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    # Google Voices
    - "lens.l.google.com"
    # Nintendo Switch
    - "*.n.n.srv.nintendo.net"
    # PlayStation
    - "+.stun.playstation.net"
    # XBox
    - "xbox.*.*.microsoft.com"
    - "*.*.xboxlive.com"
    # Microsoft
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    # Bilibili CDN
    - "*.mcdn.bilivideo.cn"
    # QQ
    - "localhost.ptlogin2.qq.com"
    # Tailscale
    - "+.ts.net"
    - "+.tailscale.com"
    - "+.tailscale.io"
  default-nameserver:
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53