##### anchor area START #####
x-dns:
  system: &x-dns-system
    - system
  china: &x-dns-china
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  overseas: &x-dns-overseas
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
##### anchor area END #####

# dns
dns:
  enable: true
  ipv6: false
  # enhanced-mode: redir-host
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "rule-set:GeneralFakeIPFilter"
    - "rule-set:MyFakeIPFilter"
  nameserver: *x-dns-overseas
  nameserver-policy:
    "rule-set:Private_domain": *x-dns-system
    "rule-set:MyDirect,MyDirect02": *x-dns-system
    "rule-set:TailscaleDERP,Tailscale_domain": *x-dns-china
    "rule-set:Tracker,PT": *x-dns-china
    "rule-set:GamesDownload,GamesDirect": *x-dns-system
    "rule-set:DeveloperDirect": *x-dns-system
    "rule-set:MicrosoftDirect,OneDrive": *x-dns-system
    "rule-set:China_domain": *x-dns-system

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - "tcp://any:53"
