# clash party format override file
# docs: https://clashparty.org/docs/guide/override/yaml

+proxies:
  # tailscale
  - name: "tailscale"
    type: tailscale
    udp: true
    exit-node: auto:any
dns:
  nameserver-policy:
    "+.ts.net": "tailscale://tailscale"

sub-rules:
  +sub-rule-private:
    - DOMAIN-SUFFIX,ts.net,PASS
    - IP-CIDR,100.64.0.0/10,PASS,no-resolve
    - IP-CIDR6,fd7a:115c:a1e0::/48,PASS,no-resolve
  +sub-rule-domain:
    - DOMAIN-SUFFIX,ts.net,tailscale
  +sub-rule-ip:
    - IP-CIDR,100.64.0.0/10,tailscale
    - IP-CIDR6,fd7a:115c:a1e0::/48,tailscale