x-proxy-providers-direct: &x-proxy-providers-direct
  type: http
  interval: 3600
  health-check:
    enable: true
    url: https://cp.cloudflare.com
    interval: 300

x-proxy-providers-relay: &x-proxy-providers-relay
  type: http
  interval: 3600
  health-check:
    enable: true
    url: https://cp.cloudflare.com
    interval: 300
  override:
    dialer-proxy: 🌏 落地中转

proxy-providers:
  # example:
  #   <<: *x-proxy-providers-direct
  #   url: "https://example.com/config.yaml"
